let productos = [{
  id: 0,
  nombre: "Camiseta adidas Afa",
  precio: 19500,
  color: "Celeste/Blanco",
  talle: ["XS","S","M","L","XL"],
  marca: "Adidas",
  deporte: "Fútbol",
  categoria: "",
  genero: "hombre",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/camisetaArgentina.jfif"
},
{
  id: 1,
  nombre: "Nike Air Max",
  precio: 29099,
  color: "Gris/Blanco",
  talle: [36.5,37,37.5,38,39.5],
  marca: "Nike",
  deporte: "Running",
  categoria: "zapatilla",
  genero: "mujer",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/nikeAirMax.jfif"
},
{
  id: 2,
  nombre: "Musculosa Topper",
  precio: 1299,
  color: "Amarillo",
  talle: ["XS","S","M","L","XL"],
  marca: "Topper",
  deporte: "Training",
  categoria: "",
  genero: "mujer",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/musculosaTopper.jfif"
},
{
  id: 3,
  nombre: "Zapatillas Puma Smiley",
  precio: 14699,
  color: "Blanco/Rojo/Azul/Amarillo",
  talle: [27,28,29,30,31,32,33,34],
  marca: "Puma",
  deporte: "Training",
  categoria: "zapatilla",
  genero: "ninio",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/zapatillaPumaSmiley.jfif"
},
{
  id: 4,
  nombre: "Pelota Umbro Neo",
  precio: 5199,
  color: "Amarillo/Celeste",
  talle: [5],
  marca: "Umbro",
  deporte: "Futbol",
  categoria: "",
  genero: "unisex",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/pelotaUmbro.jfif"
},
{
  id: 5,
  nombre: "Botines Adidas Predator",
  precio: 29899,
  color: "Naranja",
  talle: [40,41,42,43,44],
  marca: "Adidas",
  deporte: "Fútbol",
  categoria: "",
  genero: "hombre",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/botinAdidasPredator.jfif"
},
{
  id: 6,
  nombre: "Top Reebok Training",
  precio: 4999,
  color: "Negro",
  talle: ["XS","S","M","L","XL"],
  marca: "Reebok",
  deporte: "Training",
  categoria: "",
  genero: "mujer",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/topReebok.jfif"
},
{
  id: 7,
  nombre: "Short Puma Power",
  precio: 6399,
  color: "Negro",
  talle: ["XS","S","M","L","XL"],
  marca: "Puma",
  deporte: "Training",
  categoria: "",
  genero: "hombre",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: true,
  precioAnterior: 8399,
  imagen: "./media/shortPumaOferta.jfif"
},
{
  id: 8,
  nombre: "Paleta Wilson Kaos",
  precio: 47399,
  color: "Negro/Gris/Verde",
  talle: ["Único"],
  marca: "Wilson",
  deporte: "Padel",
  categoria: "",
  genero: "unisex",
  stock: 10,
  cantidadVendida: 0, 
  precioTotal: 1,
  oferta: false,
  precioAnterior: 0,
  imagen: "./media/paletaPadelWilson.jfif"
},
];